baseURL = "https://toshimitsu.tsuji.dev/"
languageCode = "ja"
title = "toshimitsu.tsuji.dev"
theme = "hugo-zen"
author = "tsujimitsu"
googleAnalytics = "UA-152694591-1"

[params]
  copyright = "tsujimitsu All rights reserved."
  twitter   = "https://twitter.com/tsujimitsu"
  facebook  = "https://www.facebook.com/tsujimitsu"
  github    = "https://github.com/tsujimitsu/"
  logo = "https://pbs.twimg.com/profile_images/972390631539556353/fYrgy6RL_400x400.jpg"
